@startuml

note  as N1 #FAEBD7
    背景颜色介绍：
        红色：非常重要 #FF5000
        绿色：重点关注 #7FFFD4
        黄色：可一般关注
        灰色：弃用 #C0C0C0
        ---简化版类图
    GenericConverter：根据源类型和目标类型上下文转换成目标类型值。
end note

interface GenericConverter
GenericConverter : +Set<ConvertiblePair> getConvertibleTypes()
GenericConverter : +Object convert(@Nullable Object source, TypeDescriptor sourceType, TypeDescriptor targetType)
interface ConditionalGenericConverter #7FFFD4
interface ConditionalConverter
ConditionalConverter : +boolean matches(TypeDescriptor sourceType, TypeDescriptor targetType)
class ArrayToCollectionConverter
ArrayToCollectionConverter : -final ConversionService conversionService
class ByteBufferConverter
ByteBufferConverter : -final ConversionService conversionService
class CollectionToStringConverter
CollectionToStringConverter : -static final String DELIMITER = ","
CollectionToStringConverter : -final ConversionService conversionService
class ConverterAdapter #FF5000
class ConverterFactoryAdapter #FF5000
class MapToMapConverter
MapToMapConverter : -final ConversionService conversionService
class StreamConverter
StreamConverter : -final ConversionService conversionService
class StringToCollectionConverter
StringToCollectionConverter : -final ConversionService conversionService

ConditionalConverter <|-- ConditionalGenericConverter


ConditionalGenericConverter <.. ArrayToCollectionConverter
ConditionalGenericConverter <.. ByteBufferConverter
ConditionalGenericConverter <.. CollectionToStringConverter
ConditionalGenericConverter <.. ConverterAdapter
ConditionalGenericConverter <.. ConverterFactoryAdapter
ConditionalGenericConverter <.. MapToMapConverter
ConditionalGenericConverter <.. StreamConverter
ConditionalGenericConverter <.. StringToCollectionConverter


GenericConverter <|-- ConditionalGenericConverter


@enduml