@startuml

note  as N1 #FAEBD7
    背景颜色介绍：
        红色：非常重要 #FF5000
        绿色：重点关注 #7FFFD4
        黄色：可一般关注
        灰色：弃用 #C0C0C0
        ---简化版类图
    ConverterFactory：生成转换成特定目标类型的Converter。
end note


interface ConverterFactory<S, R>
ConverterFactory : +<T extends R> Converter<S, T> getConverter(Class<T> targetType)
class CharacterToNumberFactory
class IntegerToEnumConverterFactory
class NumberToNumberConverterFactory
class StringToEnumConverterFactory
class StringToNumberConverterFactory


ConverterFactory <.. CharacterToNumberFactory
ConverterFactory <.. IntegerToEnumConverterFactory
ConverterFactory <.. NumberToNumberConverterFactory
ConverterFactory <.. StringToEnumConverterFactory
ConverterFactory <.. StringToNumberConverterFactory

@enduml