@startuml

note  as N1 #FAEBD7
    背景颜色介绍：
        红色：非常重要 #FF5000
        绿色：重点关注 #7FFFD4
        黄色：可一般关注
        灰色：弃用 #C0C0C0
    HandlerAdapter：作为DispatcherServlet和Handler之间的适配器。
end note

interface HandlerAdapter
HandlerAdapter : +boolean supports(Object handler)
HandlerAdapter : +ModelAndView handle(HttpServletRequest request, HttpServletResponse response, Object handler)
abstract class AbstractHandlerMethodAdapter
AbstractHandlerMethodAdapter : +boolean supports(Object handler)
AbstractHandlerMethodAdapter : +ModelAndView handle(HttpServletRequest request, HttpServletResponse response, Object handler)
AbstractHandlerMethodAdapter : #abstract boolean supportsInternal(HandlerMethod handlerMethod)
AbstractHandlerMethodAdapter : #abstract ModelAndView handleInternal()
class HttpRequestHandlerAdapter #7FFFD4
class RequestMappingHandlerAdapter #FF5000
RequestMappingHandlerAdapter : #abstract boolean supportsInternal(HandlerMethod handlerMethod)
RequestMappingHandlerAdapter : #abstract ModelAndView handleInternal()
class SimpleControllerHandlerAdapter #7FFFD4
class SimpleServletHandlerAdapter



AbstractHandlerMethodAdapter <|-- RequestMappingHandlerAdapter

HandlerAdapter <|.. AbstractHandlerMethodAdapter
HandlerAdapter <|.. HttpRequestHandlerAdapter
HandlerAdapter <|.. SimpleControllerHandlerAdapter
HandlerAdapter <|.. SimpleServletHandlerAdapter


@enduml