@startuml

note  as N1 #FAEBD7
    背景颜色介绍：
        红色：非常重要 #FF5000
        绿色：重点关注 #7FFFD4
        黄色：可一般关注
        灰色：弃用 #C0C0C0
    HttpMessageConverter：它负责将请求信息转换为一个对象（类型为T）
    或将对象（类型为T）输出为响应信息。
end note

interface HttpMessageConverter<T>
HttpMessageConverter : +boolean canRead()
HttpMessageConverter : +boolean canWrite()
HttpMessageConverter : +List<MediaType> getSupportedMediaTypes()
HttpMessageConverter : +T read()
HttpMessageConverter : +void write()
abstract class AbstractGenericHttpMessageConverter<T>
abstract class AbstractHttpMessageConverter<T>
abstract class AbstractJackson2HttpMessageConverter
abstract class AbstractJaxb2HttpMessageConverter<T>
abstract class AbstractXmlHttpMessageConverter<T>
class AllEncompassingFormHttpMessageConverter #7FFFD4
note bottom #7FFFD4:支持application/x-www-form-urlencoded,multipart/form-data
class ByteArrayHttpMessageConverter #7FFFD4
note bottom #7FFFD4:支持application/octet-stream,*/*
class FormHttpMessageConverter
interface GenericHttpMessageConverter<T>
GenericHttpMessageConverter : +void write()
class Jaxb2RootElementHttpMessageConverter #7FFFD4
note bottom #7FFFD4:支持application/xml,text/xml,application/*+xml
class MappingJackson2HttpMessageConverter #FF5000
note bottom #FF5000:支持application/json;charset=UTF-8,application/json,application/*+json
class SourceHttpMessageConverter<T extends Source>  #7FFFD4
note bottom #7FFFD4:支持application/xml,application/*+xml,text/xml
class StringHttpMessageConverter #7FFFD4
note bottom #7FFFD4:支持text/plain,*/*
class ResourceHttpMessageConverter #7FFFD4
note bottom #7FFFD4:支持*/*




AbstractGenericHttpMessageConverter <|-- AbstractJackson2HttpMessageConverter

AbstractHttpMessageConverter <|-- AbstractGenericHttpMessageConverter
AbstractHttpMessageConverter <|-- AbstractXmlHttpMessageConverter
AbstractHttpMessageConverter <|-- ByteArrayHttpMessageConverter
AbstractHttpMessageConverter <|-- ResourceHttpMessageConverter
AbstractHttpMessageConverter <|-- SourceHttpMessageConverter
AbstractHttpMessageConverter <|-- StringHttpMessageConverter

AbstractJackson2HttpMessageConverter <|-- MappingJackson2HttpMessageConverter

AbstractJaxb2HttpMessageConverter <|-- Jaxb2RootElementHttpMessageConverter

AbstractXmlHttpMessageConverter <|-- AbstractJaxb2HttpMessageConverter

FormHttpMessageConverter <|-- AllEncompassingFormHttpMessageConverter

GenericHttpMessageConverter <|.. AbstractGenericHttpMessageConverter

HttpMessageConverter <|.. AbstractHttpMessageConverter
HttpMessageConverter <|.. FormHttpMessageConverter
HttpMessageConverter <|.. GenericHttpMessageConverter

@enduml