@startuml

note  as N1 #FAEBD7
    背景颜色介绍：
        红色：非常重要 #FF5000
        绿色：重点关注 #7FFFD4
        黄色：可一般关注
        灰色：弃用 #C0C0C0
        ---简化版类图
    HandlerMethodArgumentResolver：参数解析
end note

interface HandlerMethodArgumentResolver
HandlerMethodArgumentResolver : +boolean supportsParameter()
HandlerMethodArgumentResolver : +Object resolveArgument()
abstract class AbstractMessageConverterMethodArgumentResolver
abstract class AbstractMessageConverterMethodProcessor
abstract class AbstractNamedValueMethodArgumentResolver
class ModelAttributeMethodProcessor
class RequestParamMethodArgumentResolver #FF5000
note bottom #FF5000: 上传文件
class RequestResponseBodyMethodProcessor #FF5000
note bottom #FF5000: JSON数据提交
class ServletModelAttributeMethodProcessor #FF5000
note bottom #FF5000: Form表单提交
class ServletRequestMethodArgumentResolver #FF5000
note bottom #FF5000: HttpServletRequest
class ServletResponseMethodArgumentResolver #FF5000
note bottom #FF5000: HttpServletResponse



AbstractMessageConverterMethodArgumentResolver <|-- AbstractMessageConverterMethodProcessor

AbstractMessageConverterMethodProcessor <|-- RequestResponseBodyMethodProcessor

AbstractNamedValueMethodArgumentResolver <|-- RequestParamMethodArgumentResolver

HandlerMethodArgumentResolver <|.. AbstractMessageConverterMethodArgumentResolver
HandlerMethodArgumentResolver <|.. AbstractNamedValueMethodArgumentResolver
HandlerMethodArgumentResolver <|.. ModelAttributeMethodProcessor
HandlerMethodArgumentResolver <|.. ServletRequestMethodArgumentResolver
HandlerMethodArgumentResolver <|.. ServletResponseMethodArgumentResolver


ModelAttributeMethodProcessor <|-- ServletModelAttributeMethodProcessor

@enduml