@startuml

note  as N1 #FAEBD7
    背景颜色介绍：
        红色：非常重要 #FF5000
        绿色：重点关注 #7FFFD4
        黄色：可一般关注
        灰色：弃用
    RequestBodyAdvice：可以理解为处理json输入数据的扩展点
    ResponseBodyAdvice：可以理解为处理json输出数据的扩展点
end note

interface RequestBodyAdvice
class JsonViewRequestBodyAdvice #FF5000
abstract class RequestBodyAdviceAdapter
class RequestResponseBodyAdviceChain #7FFFD4




interface ResponseBodyAdvice<T>
abstract class AbstractJsonpResponseBodyAdvice
abstract class AbstractMappingJacksonResponseBodyAdvice
class JsonViewResponseBodyAdvice #FF5000

AbstractMappingJacksonResponseBodyAdvice <|-- AbstractJsonpResponseBodyAdvice
AbstractMappingJacksonResponseBodyAdvice <|-- JsonViewResponseBodyAdvice

RequestBodyAdvice <|.. RequestBodyAdviceAdapter
RequestBodyAdvice <|.. RequestResponseBodyAdviceChain


RequestBodyAdviceAdapter <|-- JsonViewRequestBodyAdvice

ResponseBodyAdvice <|.. AbstractMappingJacksonResponseBodyAdvice
ResponseBodyAdvice <|.. RequestResponseBodyAdviceChain

@enduml