@startuml

note  as N1 #FAEBD7
    背景颜色介绍：
        红色：非常重要 #FF5000
        绿色：重点关注 #7FFFD4
        黄色：可一般关注
        灰色：弃用 #C0C0C0
        ---简化版类图
    DispatcherServlet负责接收所有Web请求，进行请求分发，
    可以认为是SpringMVC的心脏
end note

class DispatcherServlet #FF5000
abstract class FrameworkServlet
abstract class HttpServletBean



interface FlashMapManager


interface HandlerAdapter #FF5000


interface HandlerExceptionResolver #FF5000

interface HandlerMapping #FF5000

abstract class HttpServlet

interface LocaleResolver

interface MultipartResolver

interface RequestToViewNameTranslator


interface ThemeResolver


interface ViewResolver


DispatcherServlet --> FlashMapManager
DispatcherServlet --> HandlerAdapter
DispatcherServlet --> HandlerExceptionResolver
DispatcherServlet --> HandlerMapping
DispatcherServlet --> LocaleResolver
DispatcherServlet --> MultipartResolver
DispatcherServlet --> RequestToViewNameTranslator
DispatcherServlet --> ThemeResolver
DispatcherServlet --> ViewResolver


FrameworkServlet <|-- DispatcherServlet

HttpServlet <|-- HttpServletBean

HttpServletBean <|-- FrameworkServlet


@enduml