@startuml

note  as N1 #FAEBD7
    背景颜色介绍：
        红色：非常重要 #FF5000
        绿色：重点关注 #7FFFD4
        黄色：可一般关注
        灰色：弃用 #C0C0C0
    顶层鸟瞰Spring MVC相关类之间关系
end note

interface BindingResult
note bottom :代表数据绑定的结果


class DispatcherServlet
note top : 处理所有请求的分发

interface HandlerAdapter
note top : 作为DispatcherServlet和Handler之间的适配器

class HandlerExecutionChain
note top : 包含handler和HandlerInterceptor

interface HandlerExceptionResolver
note bottom : 异常处理


interface HandlerInterceptor
note bottom : Handler的执行前后对处理流程进行拦截操作

interface HandlerMapping
note top : 处理Web请求与具体请求处理控制器之间的映射关系

class HandlerMethod
note top : 一种handler

interface HandlerMethodArgumentResolver
note bottom : 参数解析

interface HttpMessageConverter
note bottom : 返回值参数转换

interface HandlerMethodReturnValueHandler
note bottom : 返回值处理

interface LocaleResolver
note bottom : 国际化支持

class ModelAndView
note bottom : 包含模型和视图

interface MultipartResolver
note bottom : 文件上传

interface ParameterNameDiscoverer
note bottom :发现方法和构造函数的参数名称

interface RequestBodyAdvice
note bottom :处理输入数据的扩展点
interface ResponseBodyAdvice
note bottom :处理输出数据的扩展点

interface RequestToViewNameTranslator
note bottom :转换逻辑视图名

interface ThemeResolver
note bottom : 主题解析

interface ThemeSource
note bottom : 管理针对各个主题的那些静态资源

interface Validator
note bottom : 数据校验

interface View
note bottom :  视图渲染

interface ViewResolver
note bottom : 逻辑视图名到View的转换


interface WebDataBinderFactory
note bottom : 创建WebDataBinder

class WebDataBinder
note right : 数据绑定


DispatcherServlet --> HandlerAdapter
DispatcherServlet --> HandlerMapping
DispatcherServlet --> HandlerExceptionResolver
DispatcherServlet --> LocaleResolver
DispatcherServlet --> MultipartResolver
DispatcherServlet --> RequestToViewNameTranslator
DispatcherServlet --> ThemeResolver
DispatcherServlet ..> ThemeSource
DispatcherServlet ..> View
DispatcherServlet ..> ViewResolver



HandlerAdapter ..> HandlerMethod
HandlerAdapter ..> ModelAndView
HandlerAdapter ..> WebDataBinderFactory

HandlerExecutionChain --> HandlerInterceptor
HandlerExecutionChain --> HandlerMethod


HandlerMapping --> HandlerMethod

HandlerMethod ..> HandlerMethodArgumentResolver
HandlerMethod ..> HandlerMethodReturnValueHandler
HandlerMethod --> ParameterNameDiscoverer

HandlerMethodArgumentResolver ..> RequestBodyAdvice

HandlerMethodReturnValueHandler ..> HttpMessageConverter
HandlerMethodReturnValueHandler ..> ResponseBodyAdvice

WebDataBinder ..> Validator
WebDataBinder ..> BindingResult

WebDataBinderFactory ..> WebDataBinder

@enduml