@startuml

note  as N1 #FAEBD7
    背景颜色介绍：
        红色：非常重要 #FF5000
        绿色：重点关注 #7FFFD4
        黄色：可一般关注
        灰色：弃用 #C0C0C0
    1.CallbackFilter：回调选择器，确定方法使用的回调
    2.accept()方法：根据上下文不同，对当前method返回不同的值i，
    这个值是在callbacks中callback对象的序号，代理运行时使用选择的
    callbacks[i]
end note


interface CallbackFilter
CallbackFilter : +int accept(Method var1)
class ProxyCallbackFilter



CallbackFilter <|.. ProxyCallbackFilter



@enduml