@startuml

note  as N1 #FAEBD7
    背景颜色介绍：
        红色：非常重要 #FF5000
        绿色：重点关注 #7FFFD4
        黄色：可一般关注
        灰色：弃用 #C0C0C0
    AopProxyFactory：根据AdvisedSupport用来决定使用什么类型的AopProxy。
end note


interface AopProxyFactory
AopProxyFactory : +AopProxy createAopProxy(AdvisedSupport config)
class DefaultAopProxyFactory #FF5000
DefaultAopProxyFactory : +AopProxy createAopProxy(AdvisedSupport config)
note bottom #FF5000 : 唯一的实现


AopProxyFactory <|-- DefaultAopProxyFactory


@enduml