@startuml

note  as N1 #FAEBD7
    背景颜色介绍：
        红色：非常重要 #FF5000
        绿色：重点关注 #7FFFD4
        黄色：可一般关注
        灰色：弃用 #C0C0C0
    Advised 承载生成代理对象所需要的必要信息，如相关目标类，Advice，Advisor等。
end note

interface TargetClassAware
interface Advised
class AdvisedSupport #FF5000
class AspectJProxyFactory
class ProxyCreatorSupport
class ProxyFactory #FF5000
class ProxyFactoryBean


class ProxyConfig




Advised <|.. AdvisedSupport
Advised <|.. AspectJProxyFactory

AdvisedSupport <|-- ProxyCreatorSupport

ProxyCreatorSupport <|-- ProxyFactory
ProxyCreatorSupport <|-- ProxyFactoryBean

ProxyConfig <|-- AdvisedSupport

TargetClassAware <|-- Advised



@enduml