@startuml

note  as N1 #FAEBD7
    背景颜色介绍：
        红色：非常重要 #FF5000
        绿色：重点关注 #7FFFD4
        黄色：可一般关注
        灰色：弃用 #C0C0C0
    AspectJAdvisorFactory：由Aspect元数据构建Advisor和Advice
end note

interface AspectJAdvisorFactory
AspectJAdvisorFactory : +List<Advisor> getAdvisors()
AspectJAdvisorFactory : +Advisor getAdvisor()
AspectJAdvisorFactory : +Advice getAdvice ();
AspectJAdvisorFactory : +boolean isAspect(Class<?> clazz)
AspectJAdvisorFactory : +void validate(Class<?> aspectClass)
abstract class AbstractAspectJAdvisorFactory
class ReflectiveAspectJAdvisorFactory #FF5000


AspectJAdvisorFactory <|.. AbstractAspectJAdvisorFactory

AbstractAspectJAdvisorFactory <|-- ReflectiveAspectJAdvisorFactory

@enduml