@startuml

note  as N1 #FAEBD7
    背景颜色介绍：
        红色：非常重要 #FF5000
        绿色：重点关注 #7FFFD4
        黄色：可一般关注
        灰色：弃用 #C0C0C0
            ---简化版类图
    MethodMatcher：描述符合织入逻辑方法的特征，验证当前方法是否匹配。
end note

interface MethodMatcher
MethodMatcher : +boolean matches(Method method, @Nullable Class<?> targetClass)
MethodMatcher : +boolean isRuntime()
MethodMatcher : +boolean matches(Method method, @Nullable Class<?> targetClass, Object... args)
MethodMatcher : +MethodMatcher TRUE = TrueMethodMatcher.INSTANCE
class AdviceExcludingMethodMatcher
class ClassFilterAwareUnionMethodMatcher
abstract class DynamicMethodMatcher
interface IntroductionAwareMethodMatcher
class IntersectionMethodMatcher
abstract class StaticMethodMatcher #FF5000
class TrueMethodMatcher
class UnionMethodMatcher

MethodMatcher <|.. DynamicMethodMatcher
MethodMatcher <|-- IntroductionAwareMethodMatcher
MethodMatcher <|.. StaticMethodMatcher
MethodMatcher <|.. TrueMethodMatcher


IntroductionAwareMethodMatcher <|.. IntersectionMethodMatcher
IntroductionAwareMethodMatcher <|.. UnionMethodMatcher


StaticMethodMatcher <|-- AdviceExcludingMethodMatcher
StaticMethodMatcher <|-- AnnotationMethodMatcher


UnionMethodMatcher <|-- ClassFilterAwareUnionMethodMatcher

@enduml