@startuml

note  as N1 #FAEBD7
    背景颜色介绍：
        红色：非常重要 #FF5000
        绿色：重点关注 #7FFFD4
        黄色：可一般关注
        灰色：弃用 #C0C0C0
        ---简化版类图
    1.Advice：织入到Joinpoint处的横切逻辑。
    <font color=red>2.per-class类型的Advice：该类型的Advice的实例可以在目标对象类的所有实例之间共享。</font>
    <font color=red>3.尽管通知定义有多种，实际实现时，我们都是基于MethodInterceptor（环绕通知）来实现的。</font>
end note

interface Advice
interface AfterAdvice
interface AfterReturningAdvice
interface BeforeAdvice
interface MethodBeforeAdvice
interface Interceptor
interface MethodInterceptor #FF5000
MethodInterceptor : +Object invoke(MethodInvocation invocation)
note right #FF5000: 相当于Around Advice，具体的实现我们自己来做
interface ThrowsAdvice
class AfterReturningAdviceInterceptor #7FFFD4
note bottom #7FFFD4: 可以理解为AfterReturningAdvice实现的对等物
class MethodBeforeAdviceInterceptor #7FFFD4
note bottom #7FFFD4: 可以理解为MethodBeforeAdvice实现的对等物
class ThrowsAdviceInterceptor #7FFFD4
note bottom #7FFFD4: 可以理解为ThrowsAdvice实现的对等物




Advice <|-- AfterAdvice
Advice <|-- BeforeAdvice
Advice <|-- Interceptor


AfterAdvice <|-- AfterReturningAdvice
AfterAdvice <|.. AfterReturningAdviceInterceptor
AfterAdvice <|-- ThrowsAdvice
AfterAdvice <|.. ThrowsAdviceInterceptor



BeforeAdvice <|--  MethodBeforeAdvice

Interceptor <|-- MethodInterceptor


MethodInterceptor <|.. AfterReturningAdviceInterceptor
MethodInterceptor <|.. MethodBeforeAdviceInterceptor
MethodInterceptor <|.. ThrowsAdviceInterceptor




@enduml