@startuml

note  as N1 #FAEBD7
    背景颜色介绍：
        红色：非常重要 #FF5000
        绿色：重点关注 #7FFFD4
        黄色：可一般关注
        灰色：弃用 #C0C0C0
    ProxyFactory: 用于生成代理对象的工厂；
        ---结果不限于是不是AOP代理对象，我们在Spring中
        用到的是AOP代理对象；
end note

interface TargetClassAware
TargetClassAware : +Class<?> getTargetClass()
interface Advised
Advised : +void setTargetSource(TargetSource targetSource)
Advised : +TargetSource getTargetSource()
Advised : +Advisor[] getAdvisors()
Advised : +void addAdvisor(Advisor advisor)
Advised : +boolean removeAdvisor(Advisor advisor)
Advised : +void addAdvice(Advice advice)
Advised : +boolean removeAdvice(Advice advice)
class AdvisedSupport
class ProxyCreatorSupport
class ProxyFactory #FF5000
ProxyFactory : -AopProxyFactory aopProxyFactory
ProxyFactory : #final synchronized AopProxy createAopProxy()
ProxyFactory : +Object getProxy()
note bottom #FF5000: 主要承担代理生成的责任，同时维护AOP上下文的责任
class ProxyFactoryBean


class ProxyConfig
ProxyConfig : -boolean proxyTargetClass
ProxyConfig : -boolean optimize
ProxyConfig : -boolean opaque
ProxyConfig : -boolean exposeProxy
ProxyConfig : -private boolean frozen



Advised <|.. AdvisedSupport

AdvisedSupport <|-- ProxyCreatorSupport

ProxyCreatorSupport <|-- ProxyFactory
ProxyCreatorSupport <|-- ProxyFactoryBean

ProxyConfig <|-- AdvisedSupport

TargetClassAware <|-- Advised



@enduml