@startuml

note  as N1 #FAEBD7
    背景颜色介绍：
        红色：非常重要
        绿色：重点关注
        黄色：可一般关注
        灰色：弃用
    这张类图表达了实现ClassFilter,MethodMatcher,Pointcut的混合类
end note

interface Pointcut
Pointcut : +ClassFilter getClassFilter()
Pointcut : +MethodMatcher getMethodMatcher()
Pointcut : +Pointcut TRUE = TruePointcut.INSTANCE
abstract class AbstractExpressionPointcut
abstract class AbstractRegexpMethodPointcut
class AspectJExpressionPointcut  #7FFFD4
class ControlFlowPointcut
abstract class DynamicMethodMatcherPointcut  #7FFFD4
class JdkRegexpMethodPointcut
class NameMatchMethodPointcut
abstract class StaticMethodMatcherPointcut #7FFFD4

interface ClassFilter

interface MethodMatcher
abstract DynamicMethodMatcher
class IntroductionAwareMethodMatcher
abstract StaticMethodMatcher



AbstractExpressionPointcut <|-- AspectJExpressionPointcut
AbstractRegexpMethodPointcut <|-- JdkRegexpMethodPointcut


ClassFilter <|.. AspectJExpressionPointcut
ClassFilter <|.. ControlFlowPointcut

DynamicMethodMatcher <|-- DynamicMethodMatcherPointcut

ExpressionPointcut <|.. AbstractExpressionPointcut


IntroductionAwareMethodMatcher <|.. AspectJExpressionPointcut

MethodMatcher <|.. ControlFlowPointcut
MethodMatcher <|.. DynamicMethodMatcher
MethodMatcher <|-- IntroductionAwareMethodMatcher
MethodMatcher <|.. StaticMethodMatcher



Pointcut ..> ClassFilter
Pointcut <|.. ControlFlowPointcut
Pointcut <|.. DynamicMethodMatcherPointcut
Pointcut <|-- ExpressionPointcut
Pointcut ..> MethodMatcher
Pointcut <|.. StaticMethodMatcherPointcut

StaticMethodMatcher <|-- StaticMethodMatcherPointcut

StaticMethodMatcherPointcut <|-- AbstractRegexpMethodPointcut
StaticMethodMatcherPointcut <|-- NameMatchMethodPointcut




@enduml