@startuml

note  as N1 #FAEBD7
   背景颜色介绍：
        红色：非常重要 #FF5000
        绿色：重点关注 #7FFFD4
        黄色：可一般关注
        灰色：弃用 #C0C0C0
end note

interface Advice
interface MethodInterceptor #FF5000
note top #FF5000: 相当于Around Advice
class ExposeInvocationInterceptor
note bottom : 确认下在AspectJ中起的作用？其排序为0

abstract class AbstractAspectJAdvice
class AspectJAfterAdvice
class AspectJAfterReturningAdvice
class AspectJAfterThrowingAdvice
class AspectJAroundAdvice #FF5000
class AspectJMethodBeforeAdvice





AbstractAspectJAdvice <|-- AspectJAfterAdvice
AbstractAspectJAdvice <|-- AspectJAfterReturningAdvice
AbstractAspectJAdvice <|-- AspectJAroundAdvice
AbstractAspectJAdvice <|-- AspectJAfterThrowingAdvice
AbstractAspectJAdvice <|-- AspectJMethodBeforeAdvice


Advice <|.. AbstractAspectJAdvice



MethodInterceptor <|.. AspectJAfterAdvice
MethodInterceptor <|.. AspectJAfterThrowingAdvice
MethodInterceptor <|.. AspectJAroundAdvice
MethodInterceptor <|.. ExposeInvocationInterceptor





@enduml