@startuml

note  as N1 #FAEBD7
    背景颜色介绍：
        红色：非常重要
        绿色：重点关注
        黄色：可一般关注
        灰色：弃用
    GeneratorStrategy.generate()方法生成代理类的字节码。
end note




interface GeneratorStrategy
GeneratorStrategy : byte[] generate(ClassGenerator var1)
class DefaultGeneratorStrategy
class UndeclaredThrowableStrategy
class ClassLoaderAwareUndeclaredThrowableStrategy
note right : 保证我们设置的ClassLoader能够生效



DefaultGeneratorStrategy <|-- UndeclaredThrowableStrategy


GeneratorStrategy <|.. DefaultGeneratorStrategy


UndeclaredThrowableStrategy <|-- ClassLoaderAwareUndeclaredThrowableStrategy

@enduml