@startuml

note  as N1 #FAEBD7
    背景颜色介绍：
        红色：非常重要 #FF5000
        绿色：重点关注 #7FFFD4
        黄色：可一般关注
        灰色：弃用 #C0C0C0
            ---简化版类图
    AspectJExpressionPointcut：AspectJ类型的注解Pointcut声明
    在Spring中表示形式。
end note

class AspectJExpressionPointcut #FF5000
interface Pointcut
Pointcut : +ClassFilter getClassFilter()
Pointcut : +MethodMatcher getMethodMatcher()
Pointcut : +Pointcut TRUE = TruePointcut.INSTANCE
abstract class AbstractExpressionPointcut
AbstractExpressionPointcut : +String getExpression()
AbstractExpressionPointcut : +void setExpression(@Nullable String expression)
interface ExpressionPointcut
ExpressionPointcut : +String getExpression()


interface ClassFilter
ClassFilter : +boolean matches(Class<?> clazz)

interface MethodMatcher
MethodMatcher : +boolean isRuntime()
MethodMatcher : +boolean matches()
interface IntroductionAwareMethodMatcher
IntroductionAwareMethodMatcher : +boolean matches()

AbstractExpressionPointcut <|-- AspectJExpressionPointcut


ClassFilter <|.. AspectJExpressionPointcut

ExpressionPointcut <|.. AbstractExpressionPointcut

IntroductionAwareMethodMatcher <|.. AspectJExpressionPointcut

MethodMatcher <|-- IntroductionAwareMethodMatcher

Pointcut <|-- ExpressionPointcut




@enduml