@startuml

note  as N1 #FAEBD7
    背景颜色介绍：
        红色：非常重要
        绿色：重点关注
        黄色：可一般关注
        灰色：弃用
    1.CallbackFilter：回调选择器，有选择的对一些方法使用回调
    2.accept()根据不同的method返回不同的值i，这个值是在callbacks中callback对象的序号，
    就是调用了callbacks[i]
end note


interface CallbackFilter
CallbackFilter : +int accept(Method var1)
class ProxyCallbackFilter



CallbackFilter <|.. ProxyCallbackFilter



@enduml