@startuml

note  as N1 #FAEBD7
    背景颜色介绍：
        红色：非常重要
        绿色：重点关注
        黄色：可一般关注
        灰色：弃用
end note


interface BindingResult
abstract class AbstractBindingResult
abstract class AbstractPropertyBindingResult
class BeanPropertyBindingResult #FF5000
class BindException
class DirectFieldBindingResult
class MapBindingResult
class WebExchangeBindException



AbstractBindingResult <|-- AbstractPropertyBindingResult
AbstractBindingResult <|-- MapBindingResult


AbstractPropertyBindingResult <|-- BeanPropertyBindingResult
AbstractPropertyBindingResult <|-- DirectFieldBindingResult


BindingResult <|.. AbstractBindingResult
BindingResult <|.. BindException
BindingResult <|.. WebExchangeBindException


@enduml