@startuml

note  as N1 #FAEBD7
    背景颜色介绍：
        红色：非常重要 #FF5000
        绿色：重点关注 #7FFFD4
        黄色：可一般关注
        灰色：弃用 #C0C0C0
        MergedBeanDefinitionPostProcessor：为bean实例属性填充做准备，
        检查是否有注解，验证使用是否正确，标记结果
end note

interface MergedBeanDefinitionPostProcessor
MergedBeanDefinitionPostProcessor : +void postProcessMergedBeanDefinition()
class ApplicationListenerDetector
class AutowiredAnnotationBeanPostProcessor #7FFFD4
interface BeanPostProcessor
class CommonAnnotationBeanPostProcessor  #7FFFD4
class InitDestroyAnnotationBeanPostProcessor
class JmsListenerAnnotationBeanPostProcessor
class PersistenceAnnotationBeanPostProcessor
class RequiredAnnotationBeanPostProcessor
class ScheduledAnnotationBeanPostProcessor #7FFFD4


BeanPostProcessor <|-- MergedBeanDefinitionPostProcessor


InitDestroyAnnotationBeanPostProcessor <|-- CommonAnnotationBeanPostProcessor

MergedBeanDefinitionPostProcessor <|.. ApplicationListenerDetector
MergedBeanDefinitionPostProcessor <|.. AutowiredAnnotationBeanPostProcessor
MergedBeanDefinitionPostProcessor <|.. InitDestroyAnnotationBeanPostProcessor
MergedBeanDefinitionPostProcessor <|.. JmsListenerAnnotationBeanPostProcessor
MergedBeanDefinitionPostProcessor <|.. PersistenceAnnotationBeanPostProcessor
MergedBeanDefinitionPostProcessor <|.. RequiredAnnotationBeanPostProcessor
MergedBeanDefinitionPostProcessor <|.. ScheduledAnnotationBeanPostProcessor

@enduml