@startuml

note  as N1 #FAEBD7
    背景颜色介绍：
        红色：非常重要 #FF5000
        绿色：重点关注 #7FFFD4
        黄色：可一般关注
        灰色：弃用 #C0C0C0
    BeanDefinitionDocumentReader：XmlBeanDefinitionReader类型bean定义解析时委托给它了。
end note


interface BeanDefinitionDocumentReader
BeanDefinitionDocumentReader : void registerBeanDefinitions(Document doc, XmlReaderContext readerContext)
class DefaultBeanDefinitionDocumentReader






BeanDefinitionDocumentReader <|.. DefaultBeanDefinitionDocumentReader



@enduml