@startuml

note  as N1 #FAEBD7
    背景颜色介绍：
        红色：非常重要 #FF5000
        绿色：重点关注 #7FFFD4
        黄色：可一般关注
        灰色：弃用 #C0C0C0
    了解BeanPostProcessor对Bean的影响，对于深入理解Spring核心功能的工作原理将会有很大的帮助。
    很多Spring扩展插件或Spring子项目都是使用这些后处理器完成激动人心的功能的。
end note

interface BeanPostProcessor  #7FFFD4
abstract class AbstractAdvisorAutoProxyCreator
abstract class AbstractAutoProxyCreator #FF5000
AbstractAutoProxyCreator : +Object postProcessBeforeInstantiation()
AbstractAutoProxyCreator : #abstract Object[] getAdvicesAndAdvisorsForBean()
note top #FF5000: 自动代理的核心:postProcessBeforeInstantiation()是AbstractAutoProxyCreator这一脉络中唯一的实现
class AnnotationAwareAspectJAutoProxyCreator #FF5000
note bottom #FF5000 : 自动代理：对@AspectJ形式的Spring AOP支持,也支持传统的
class AspectJAwareAdvisorAutoProxyCreator
class BeanNameAutoProxyCreator #7FFFD4
class DefaultAdvisorAutoProxyCreator #FF5000
note bottom #FF5000: 自动代理：搜索所有实现Advisor接口的Spring AOP支持
class InfrastructureAdvisorAutoProxyCreator
interface InstantiationAwareBeanPostProcessor  #7FFFD4
interface SmartInstantiationAwareBeanPostProcessor

class ProxyConfig
class ProxyProcessorSupport


AbstractAutoProxyCreator <|-- AbstractAdvisorAutoProxyCreator
AbstractAutoProxyCreator <|-- BeanNameAutoProxyCreator



AbstractAdvisorAutoProxyCreator <|-- AspectJAwareAdvisorAutoProxyCreator
AbstractAdvisorAutoProxyCreator <|-- DefaultAdvisorAutoProxyCreator
AbstractAdvisorAutoProxyCreator <|-- InfrastructureAdvisorAutoProxyCreator


AspectJAwareAdvisorAutoProxyCreator <|-- AnnotationAwareAspectJAutoProxyCreator



BeanPostProcessor <|-- InstantiationAwareBeanPostProcessor


InstantiationAwareBeanPostProcessor <|-- SmartInstantiationAwareBeanPostProcessor


ProxyConfig <|-- ProxyProcessorSupport
ProxyProcessorSupport <|-- AbstractAutoProxyCreator

SmartInstantiationAwareBeanPostProcessor <.. AbstractAutoProxyCreator

@enduml