@startuml

note  as N1 #FAEBD7
    背景颜色介绍：
        红色：非常重要
        绿色：重点关注
        黄色：可一般关注
        灰色：弃用
        ---简化版类图
    FactoryBean是Spring容器提供的一种可以扩展容器实例化逻辑的接口。用户可以通过实现该
    工厂类接口定制实例化Bean的逻辑，隐藏实例化一些复杂Bean的细节，给上层调用带来了便利。
    如果一定要获取FactoryBean本身的话，可以通过在getBean(&beanId)来达到目的。
end note


interface FactoryBean<T>
FactoryBean : +T getObject()
FactoryBean : +Class<?> getObjectType()
FactoryBean : +boolean isSingleton()
note top : getObject()返回由FactoryBean创建的Bean实例
abstract class AbstractSingletonProxyFactoryBean
class CacheProxyFactoryBean
class ConversionServiceFactoryBean
class JndiObjectFactoryBean
class LocalSessionFactoryBean
class ProxyFactoryBean
class TransactionProxyFactoryBean

AbstractSingletonProxyFactoryBean <|-- CacheProxyFactoryBean
AbstractSingletonProxyFactoryBean <|-- TransactionProxyFactoryBean

FactoryBean <|.. AbstractSingletonProxyFactoryBean
FactoryBean <|.. ConversionServiceFactoryBean
FactoryBean <|.. JndiObjectFactoryBean
FactoryBean <|.. LocalSessionFactoryBean
FactoryBean <|.. ProxyFactoryBean



@enduml