@startuml

note  as N1 #FAEBD7
    背景颜色介绍：
        红色：非常重要 #FF5000
        绿色：重点关注 #7FFFD4
        黄色：可一般关注
        灰色：弃用 #C0C0C0
        ---简化版类图
    DestructionAwareBeanPostProcessor：bean的生命周期相关的BeanPostProcessor。
end note


interface DestructionAwareBeanPostProcessor
DestructionAwareBeanPostProcessor : +void postProcessBeforeDestruction()
DestructionAwareBeanPostProcessor : +default boolean requiresDestruction(Object bean)
interface BeanPostProcessor
class ApplicationListenerDetector
class CommonAnnotationBeanPostProcessor #7FFFD4
class InitDestroyAnnotationBeanPostProcessor #7FFFD4
class PersistenceAnnotationBeanPostProcessor #7FFFD4
class ScheduledAnnotationBeanPostProcessor #7FFFD4




BeanPostProcessor <|-- DestructionAwareBeanPostProcessor



DestructionAwareBeanPostProcessor <|.. ApplicationListenerDetector
DestructionAwareBeanPostProcessor <|.. InitDestroyAnnotationBeanPostProcessor
DestructionAwareBeanPostProcessor <|.. PersistenceAnnotationBeanPostProcessor
DestructionAwareBeanPostProcessor <|.. ScheduledAnnotationBeanPostProcessor

InitDestroyAnnotationBeanPostProcessor <|-- CommonAnnotationBeanPostProcessor



@enduml