@startuml

note  as N1 #FAEBD7
    背景颜色介绍：
        红色：非常重要 #FF5000
        绿色：重点关注 #7FFFD4
        黄色：可一般关注
        灰色：弃用 #C0C0C0
        ---简化版类图
    BeanPostProcessor：可以对Bean实例生成进行干预，比如Spring AOP就是
    以此为桥梁实现的。
end note

interface BeanPostProcessor
abstract class AbstractAdvisingBeanPostProcessor #7FFFD4
class ApplicationContextAwareProcessor #7FFFD4
class BeanValidationPostProcessor
interface DestructionAwareBeanPostProcessor #7FFFD4
interface InstantiationAwareBeanPostProcessor  #7FFFD4
interface MergedBeanDefinitionPostProcessor #7FFFD4
class ServletContextAwareProcessor


BeanPostProcessor <|-- AbstractAdvisingBeanPostProcessor
BeanPostProcessor <|.. ApplicationContextAwareProcessor
BeanPostProcessor <|.. BeanValidationPostProcessor
BeanPostProcessor <|-- DestructionAwareBeanPostProcessor
BeanPostProcessor <|-- InstantiationAwareBeanPostProcessor
BeanPostProcessor <|-- MergedBeanDefinitionPostProcessor
BeanPostProcessor <|-- ServletContextAwareProcessor



@enduml