@startuml

note  as N1 #FAEBD7
    背景颜色介绍：
        红色：非常重要 #FF5000
        绿色：重点关注 #7FFFD4
        黄色：可一般关注
        灰色：弃用 #C0C0C0
    顶层鸟瞰AOP类之间关系
end note

interface Advice
note bottom : 要织入的业务逻辑
interface MethodInterceptor
note bottom : 前置，后置，异常通知统统转换为环绕通知


class AdvisedSupport
AdvisedSupport : -Advisor[] advisorArray
AdvisedSupport : -List<Advisor> advisors
AdvisedSupport : ~TargetSource targetSource
AdvisedSupport : +void addAdvisor(Advisor advisor)
AdvisedSupport : +void addAdvice(Advice advice)
note bottom : 承载生成代理对象所需的必要信息，如目标类，Advice,Advisor等

interface Advisor
note top : 包含Advice,Pointcut


interface AopProxy
AopProxy : +Object getProxy()
AopProxy : +Object getProxy(@Nullable ClassLoader classLoader)
note top : 对不同的代理实现进行了适度的抽象，实现类用于生成代理对象。


interface AopProxyFactory
AopProxyFactory : +AopProxy createAopProxy(AdvisedSupport config)
note top : 根据AdvisedSupport用来决定生成什么类型的AopProxy。

interface Joinpoint
note bottom : 执行点
class ReflectiveMethodInvocation
note bottom : 执行点，具体执行织入逻辑和目标对象方法


interface Pointcut
note bottom : 用于描述执行点集合

Advice <|-- MethodInterceptor

AdvisedSupport --> Advisor

Advisor --> Advice
Advisor --> Pointcut


AopProxy ..> Joinpoint

AopProxyFactory ..> AopProxy
AopProxyFactory ..> AdvisedSupport

Joinpoint <|.. ReflectiveMethodInvocation

ReflectiveMethodInvocation --> Advice

@enduml