@startuml
autonumber

-> RequestMappingHandlerMapping: afterPropertiesSet()
activate RequestMappingHandlerMapping #DarkSalmon

note left of RequestMappingHandlerMapping #FAEBD7
    *介绍初始化时注册所有Handler的过程。
        ---这里只描述了主要步骤
end note
    note right of RequestMappingHandlerMapping #aqua
        1.构建上下文信息：设置urlPathHelper，pathMatcher从继承类中获得及其他默认设置
        2.调用继承类的afterPropertiesSet()
    end note

    RequestMappingHandlerMapping -> AbstractHandlerMethodMapping : afterPropertiesSet()
    activate AbstractHandlerMethodMapping #DarkSalmon

        AbstractHandlerMethodMapping -> AbstractHandlerMethodMapping : initHandlerMethods()

            AbstractHandlerMethodMapping -> DefaultListableBeanFactory : getBeanNamesForType():查找所有bean名称
            activate DefaultListableBeanFactory #DarkSalmon
            DefaultListableBeanFactory --> AbstractHandlerMethodMapping : String[] beanNames
            deactivate DefaultListableBeanFactory

            loop String beanName : beanNames
                note right of AbstractHandlerMethodMapping #aqua
                    过滤scopedTarget.开头的bean名称
                end note
                AbstractHandlerMethodMapping -> AbstractBeanFactory : getType() :获取class信息
                activate AbstractBeanFactory #DarkSalmon
                AbstractBeanFactory --> AbstractHandlerMethodMapping
                deactivate AbstractBeanFactory

                AbstractHandlerMethodMapping -> RequestMappingHandlerMapping : isHandler()
                activate RequestMappingHandlerMapping #DarkSalmon
                    note right of RequestMappingHandlerMapping #FF5000
                        判断是否包含@Controller或@RequestMapping注解
                    end note
                RequestMappingHandlerMapping --> AbstractHandlerMethodMapping
                deactivate RequestMappingHandlerMapping

                alt 包含@Controller或@RequestMapping注解

                    note right of AbstractHandlerMethodMapping #aqua
                        1.获取这个类中所有含@RequestMapping注解的方法，组装成RequestMappingInfo(含有匹配路径，HttpMethod类型)
                        2.遍历获取每个方法Method（便于后面反射调用），最终包含在HandlerMethod中使用
                    end note
                    AbstractHandlerMethodMapping -> AbstractHandlerMethodMapping : detectHandlerMethods()
                    activate AbstractHandlerMethodMapping #DarkSalmon

                        loop
                            AbstractHandlerMethodMapping -> AbstractHandlerMethodMapping : registerHandlerMethod()
                            activate AbstractHandlerMethodMapping #DarkSalmon

                                AbstractHandlerMethodMapping -> MappingRegistry : register()
                                activate MappingRegistry #DarkSalmon
                                    note right of MappingRegistry #FF5000
                                        1.组装HandlerMethod：含有beanName,BeanFactory,method
                                        2.同时注册其他辅助信息，便于查找匹配
                                        3.最终注册为MappingRegistration：含有RequestMappingInfo，
                                            HandlerMethod,匹配路径，简化的名称(类名中大写字母#方法名)
                                    end note
                                MappingRegistry --> AbstractHandlerMethodMapping
                                deactivate MappingRegistry

                            deactivate AbstractHandlerMethodMapping
                        end

                    deactivate AbstractHandlerMethodMapping
                end

            end


        activate AbstractHandlerMethodMapping #DarkSalmon
        deactivate AbstractHandlerMethodMapping

    AbstractHandlerMethodMapping -> RequestMappingHandlerMapping
    deactivate AbstractHandlerMethodMapping

<-- RequestMappingHandlerMapping
deactivate RequestMappingHandlerMapping

note right of RequestMappingHandlerMapping #FAEBD7
    *总结
        主要就是准备素材：获取所有标注@Controller或@RequestMapping注解的bean，
            把里面的方法含@RequestMapping注解的方法，转换成HandlerMethod，并注册。
            ---注意是注册到AbstractHandlerMethodMapping中MappingRegistry字段中，非容器中
    *备注
        1.MethodIntrospector：方法的工具类

end note

@enduml