@startuml
autonumber



-> RequestMappingHandlerMapping: getHandler()
activate RequestMappingHandlerMapping #DarkSalmon

    note right of RequestMappingHandlerMapping #FAEBD7
        *介绍获得Handler的过程
            ---这里只描述了主要步骤
    end note

    RequestMappingHandlerMapping -> AbstractHandlerMapping : getHandler()
    activate AbstractHandlerMapping #DarkSalmon

        AbstractHandlerMapping -> AbstractHandlerMethodMapping : getHandlerInternal()
        activate AbstractHandlerMethodMapping #DarkSalmon

            AbstractHandlerMethodMapping -> UrlPathHelper :getLookupPathForRequest():获取请求路径
            activate UrlPathHelper #DarkSalmon
            UrlPathHelper --> AbstractHandlerMethodMapping : lookupPath
            deactivate UrlPathHelper

            note right of AbstractHandlerMethodMapping #aqua
                1.根据请求路径查询匹配的Match;
                2.处理匹配的几种可能性：
                    a.正好找到一个或多个：
                        I.排序
                        II.当非跨域请求时，有两个同时匹配抛出异常；
                        III.返回第一个匹配的---一般情况
                    b.没有匹配的，由上下文来决定是返回结果：null，异常等
            end note
            AbstractHandlerMethodMapping -> AbstractHandlerMethodMapping : lookupHandlerMethod() : handlerMethod
            activate AbstractHandlerMethodMapping #DarkSalmon
            deactivate AbstractHandlerMethodMapping

            alt handlerMethod != null

                note right of AbstractHandlerMethodMapping #aqua
                    如果HandlerMethod.bean属性为字符串，转换为Bean实例
                end note

                AbstractHandlerMethodMapping -> HandlerMethod : createWithResolvedBean() : handlerMethod：
                activate HandlerMethod #DarkSalmon
                HandlerMethod --> AbstractHandlerMethodMapping : handlerMethod
                deactivate HandlerMethod

            end

        AbstractHandlerMethodMapping --> AbstractHandlerMapping : HandlerMethod
        deactivate AbstractHandlerMethodMapping

        alt 没有匹配到，查询默认的
            AbstractHandlerMapping -> AbstractHandlerMapping : getDefaultHandler()
            activate AbstractHandlerMapping #DarkSalmon
            deactivate AbstractHandlerMapping
        end

        alt 最终没有匹配的，返回null
<--AbstractHandlerMapping : null
        end

        note right of AbstractHandlerMapping #aqua
            组装HandlerExecutionChain，含有：
                HandlerMethod
                HandlerInterceptor
        end note
        AbstractHandlerMapping -> AbstractHandlerMapping : getHandlerExecutionChain() : HandlerExecutionChain
        activate AbstractHandlerMapping #DarkSalmon
        deactivate AbstractHandlerMapping

    AbstractHandlerMapping -> RequestMappingHandlerMapping : handlerExecutionChain
    deactivate AbstractHandlerMapping

<-- RequestMappingHandlerMapping: handlerExecutionChain
deactivate RequestMappingHandlerMapping

note right of RequestMappingHandlerMapping #FAEBD7
    *总结
        查询符合条件的HandlerMethod和HandlerInterceptor
end note

@enduml